name: gen_coverage
version: 0.0.1
description: >-
  CLI utility to painlessly generate lcov coverage reports for your
  dart package and enforce minimum coverage.
publish_to: none # for now
repository: https://github.com/civts/gen-coverage
issue_tracker: https://github.com/civts/gen-coverage/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  gen_coverage: main

dependencies:
  args: ^2.0.0
  coverage: ^1.0.2
  path: ^1.7.0
  test: ^1.16.8

dev_dependencies:
  dartdoc: ^0.42.0
  effective_dart: ^1.3.1
